rmdir "gh-pages" /s /q
rmdir "gh-pages-git" /s /q
git clone --depth=1 -b gh-pages https://github.com/AndreyAkinshin/aakinshin.net gh-pages
mkdir "gh-pages-git"
xcopy "gh-pages/.git" "gh-pages-git/.git" /i /s /y /h
rmdir "gh-pages" /s /q
mkdir "gh-pages"
xcopy "web/_site" "gh-pages" /i /s /y /h
xcopy "gh-pages-git" "gh-pages" /i /s /y /h
rmdir "gh-pages-git" /s /q
cd gh-pages
git add -A
git commit -m "Autogenerated"
git log -1
git push
cd ..